### ISSUE TITLE
Fails to tag hidden files on upload.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#4]
If you try something like this.

*.binary binary binary
*.rft ISO8859-1 IBM-1047
*.asciitext ISO8859-1 ISO8859-1
*.project binary binary
*.nodejsapp binary binary
*.hidden binary binary

And upload files called .hidden (was empty) and .project ( with something in it)
Neither of these files get tagged as binary. 

This occurs if they are nested or in the top level directory.

**Comment by ChrisAtkinson1** [comment]
I note also when running in automation - they do not get put in the directory they should be either.

I suspect this is a base bug.

This can be recreated manually by specifying a directory that needs to be created on zfS

**Comment by matthewpwilson** [comment]
Fixed.

**Comment by ChrisAtkinson1** [comment]
It now does not even upload the .hidden files!

**Comment by matthewpwilson** [comment]
I think this is a base issue and was regressed by a fix they put through recently. Suggest raising on the main zowe-cli repo.

**Comment by matthewpwilson** [comment]
I've raised https://github.com/zowe/zowe-cli/issues/312 to find out if this was intentional
