### ISSUE TITLE
Putting in an invalid codepage sees an empty file created on z/FS 

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#5]
I put an invalid codepage in my .zosattributes.

I have a simple png file ( that has data in it).

*.png binary bacon

An empty file is created on z/OS and this error is returned.  

I believe the error is correct - but should the empty file be created ??

Error is returned on upload request as 
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 16
rc:       147
reason:   -1033961426
message:  Illegal character sequence detected by iconv()
details:
  - EDC5147I Illegal byte sequence. (errno2=0xC25F002E)

Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      winmvs26.hursley.ibm.com
Port:      32070
Base Path:
Resource:  /zosmf/restfiles/fs/u/atkinc/jesttest/pic.png

**Comment by ChrisAtkinson1** [comment]
Same thing occurs if the from value is incorrect.

Eg

*.png eggs binary

**Comment by ChrisAtkinson1** [comment]
And the wrong way round...

*.png IBM-1047 ISO8859-1

**Comment by ChrisAtkinson1** [comment]
Note with a text file - slightly different behaviour.

This error if the codepage is invalid on USS
Untitled 
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 1
rc:    8
reason:  9
message: Error executing command. exit_code=1
details:
 - /bin/chtag -t -c bacon /u/atkinc/jesttest/my.txt
 - FSUMF174 chtag: You must enter a codeset name or a ccsid between 0 and 65535 (USHRT_MAX).
Collapse
Which is correct.
If the codepage is invalid locally ( my eggs IBM-1047) one.  It is uploaded and created with correct tag.  I think that is mentioned in your document.

Comment from Matthew
Yes that makes sense, as the content is text the conversion works OK so we go on to tag it.
Hmm you know I don't think I actually ever pass through the local encoding to the z/OSMF call, otherwise I would expect the eggs case to fail

**Comment by matthewpwilson** [comment]
I've now updated the code to upload using the specified local encoding. Everything else described here is a limitation of the z/OSMF files API.
