### ISSUE TITLE
Some characters in a wild card that is invalid see the file incorrectly tagged.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [matthewpwilson/zowe-cli#6]
I have this in my properties file

*.pn!g binary binary
*.txt ISO8859 IBM-1047

On upload the png file is tagged with the following lines wildcard.

/u/atkinc/jesttest:>chtag -p *
t IBM-1047    T=on  my.txt
t ISO8859-1   T=on  pic.png

The png file seems to pick up a default tag.  I assume this is the correct default but I am not certain if this is supposed to be the case with binary files ??

**Comment by matthewpwilson** [comment]
I think this is reasonable behaviour - *.pn!g is not matching pic.png so it just gets the default treatment. We don't try to examine the file to see that it's binary.
